# https://taskfile.dev

version: "3"

tasks:
  clear:
    vars:
      PROJECT_NAME: "go-template-echo"
    cmds:
      - rm -f ./{{.PROJECT_NAME}} coverage.out
      - rm -rf base/*

  build:
    cmds:
      - go build .
    silent: true

  build-release:
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h
      GIT_BRANCH:
        sh: git name-rev --name-only {{.GIT_COMMIT}}
      BUILDNUM: '{{.BUILDNUM| default "1"}}'
      BUILD_TIMESTAMP:
        sh: date -u +'%Y-%m-%dT%H:%M:%SZ'
    cmds:
      - go build -ldflags="-X main.aGitHash={{.GIT_COMMIT}} -X main.aGitBranch={{.GIT_BRANCH}} -X main.aBuildNumber={{.BUILDNUM}} -X main.aBuildTimeStamp={{.BUILD_TIMESTAMP}}" .

  gen-apidoc:
    cmds:
      - mkdir -p spec
      - go-swagger3 --module-path . --output spec/docs.json --schema-without-pkg

  lint:
    cmds:
      - golangci-lint run ./...

  test:
    cmds:
      - go test ./... -v --coverprofile=coverage.out
    silent: true
