definitions:
  structs.JSONResult:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact:
    email: support@misko.su
    name: API Example
    url: http://misko.su/support
  description: This is a example api-server.
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: go-template-echo
  version: "1.0"
paths:
  /v1/test:
    get:
      description: Test method
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.JSONResult'
      summary: Test method
      tags:
      - v1
swagger: "2.0"
